name: Continuous Deployment # Pipeline that deploys code to AWS

on:
  workflow_run: # CD triggers AFTER CI completes successfully
    workflows: ["Continuous Integration"] # Waits for CI pipeline to pass
    types:
      - completed # Triggers when CI workflow finishes
    branches: [ main ]
  workflow_dispatch:  # Also allow manual trigger - useful for re-deploying without making a code change

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest # Fresh Ubuntu runner from GitHub
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }} # Only deploy if CI passed or manually triggered
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v7 # Downloads repo code onto the runner
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      
      - name: Set up Node.js # Needed for CDK CLI
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Configure AWS credentials # Authenticates the runner with AWS 
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Reads the access key from GitHub Secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Reads secret key from GitHub secrets. Both are never exposed in logs or code
          aws-region: us-east-1 
      
      - name: Install CDK
        run: npm install -g aws-cdk
      
      - name: Install CDK dependencies
        run: |
          cd cdk-app
          pip install -r requirements.txt
      
      - name: Build Lambda Layer # LambdaStack references this folder so must be built before cdk deploy
        run: |
          mkdir -p lambda-layer/python
          pip install --platform manylinux2014_x86_64 --only-binary=:all: --python-version 311 yfinance -t lambda-layer/python 
      
      - name: CDK Deploy # Deploys everything to AWS in correct dependency order
        run: |
          cd cdk-app
          cdk deploy --all --require-approval never
      
      - name: Verify deployment # After deployment, verifies the API and Dashboard are actually working
        run: |
          echo "Testing API health endpoint..."
          curl -f https://1hdrnjh4kl.execute-api.us-east-1.amazonaws.com/prod/health || exit 1
          echo "Testing dashboard..."
          curl -f https://dqdtse490mbv1.cloudfront.net || exit 1
          echo "Deployment verified successfully!"
# CDK compares current state in AWS with the new code and only deploys changes. This is the step that takes code from source (GitHub) to end user (AWS)